export const actionConstants = {
  login_success: 'login_success',
  sign_up_success: 'sign_up_success',
  log_out_success: 'log_out_success',
  log_out_failure: 'log_out_failure',
  show_loader: 'show_loader',
  save_user: 'save_user',
  error_handler: 'error_handler',
  exception_handler: 'exception_handler',
  action_type: 'type',
  user_data: 'user_data',
  user_response: 'user_response',
  user_profile: 'user_profile',
  host_user_profile: 'host_user_profile',
  terms_conditions: 'terms_conditions',
  status_bar: 'status_bar',
};
